# Generated by Django 3.1.4 on 2021-04-30 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210429_0728'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='ip',
            field=models.CharField(default='0.0.0.0', max_length=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='wifi_password',
            field=models.CharField(default='password', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='device',
            name='wifi_ssid',
            field=models.CharField(default='ssid', max_length=20),
            preserve_default=False,
        ),
    ]
