# Generated by Django 3.1.4 on 2021-04-30 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210430_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.farm'),
        ),
    ]
